services:

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:${WG_EASY_VERSION:-latest}
    env_file: environment.d/wg-easy.env
    environment:
      WG_HOST: ${WG_HOST}
      PASSWORD_HASH: ${PASSWORD_HASH}
    cap_add: [NET_ADMIN, SYS_MODULE]
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    networks:
      wireguard:
        ipv4_address: 10.42.42.42
        ipv6_address: fdcc:ad94:bacf:61a3::2a
    ports:
      - ${WIREGUARD_PORT:-51820}:51820/udp
      - ${WEB_UI_PORT:-51821}:51821/tcp
    volumes:
      - ${WIREGUARD_CONFIG_PATH:-wireguard-config}:/etc/wireguard
      - /etc/localtime:/etc/localtime:ro
      - /lib/modules:/lib/modules:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
  
  watchtower:
    image: containrrr/watchtower:${WATCHTOWER_VERSION:-latest}
    env_file: environment.d/watchtower.env
    environment:
      WATCHTOWER_SCOPE: ${COMPOSE_PROJECT_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

networks:
  wireguard:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64

volumes:
  wireguard-config: {}
