services:

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:${WG_EASY_VERSION:-latest}
    env_file: environment.d/wg-easy.env
    environment:
      WG_HOST: ${WG_HOST}
      PASSWORD_HASH: ${PASSWORD_HASH}
    cap_add: 
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - ${WIRGUARD_PORT:-51820}:51820
      - ${WEB_UI_PORT:-51821}:51821
    volumes:
      - ${WIREGUARD_CONFIG_PATH:-wireguard-config}:/etc/wireguard
      - /etc/localtime:/etc/localtime:ro
    # healthcheck:
    #   test: "curl http://localhost:3000/api/heartbeat"
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
  
  watchtower:
    image: containrrr/watchtower:${WATCHTOWER_VERSION:-latest}
    env_file: environment.d/watchtower.env
    environment:
      WATCHTOWER_SCOPE: ${COMPOSE_PROJECT_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.scope: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

volumes:
  wireguard-config: {}
